version: '3.8'

services:
  web-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: local_notebooklm_ui
    ports:
      - "7860:7860"
    command: ["python", "docker/web_ui.py"]
    volumes:
      - ..:/app

  api-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: local_notebooklm_api
    ports:
      - "8000:8000"
    command: ["python", "docker/server.py"]
    volumes:
      - ..:/app